### ISSUE TITLE
Add property to grab the HTML body that is ready for conversion to PDF.

### ISSUE THREAD

**Issue by vs2ds** [TeamMsgExtractor/msg-extractor#102]
this is only a request, mods please delete if irrelevant.

**Comment by TheElementalOfCreation** [comment]
Tools for converting HTML to pdf exist, and HTML output (if it exists) is already supported here.

**Comment by TheElementalOfDestruction** [comment]
So it is now 2022 and I'm properly reopening this issue, rebranding it, and marking it as an accepted feature request. 

Here are the details you need to know. Version 0.29.0 was a full update to how things are saved and handled, including the HTML and RTF bodies. Now that this is being handled well, I can add support for using the existing HTML body to form a stream that could directly be converted from HTML to pdf (using, for example, a tool like `wkhtmltopdf`). A long time ago I made some code that sort of did this, although it was poor and rather rudimentary. Soon I'll reopen that code and look at it for the first time in years to see if I can polish it enough to actually add it to this module. It will likely be either in or after version 0.30.0, and I'll keep you updated on when it will be coming out. 

Additionally, issue #225 is around adding support for extracting encapsulated HTML from the RTF body, which will allow for more files to take advantage of this feature.

Let me know what you think and if anything else should be done.

**Comment by TheElementalOfDestruction** [comment]
Apparently I forgot to say it but this should now be properly implemented. `--prepared-html` can be used from the command line with the `--html` option to output the formatted html. Additionally, `MessageBase.htmlBodyPrepared` contains the bytes for the prepared body (does not include the injected header), and `Message.save` now has an option `preparedHtml` for turning on this feature.

**Comment by TheElementalOfDestruction** [comment]
So uh hi... Been a little bit, and we have a new update... This is now officially something you can do in version 0.34.0, you can directly save the body into a PDF from the save function.  From the save function, give the keyword parameter `pdf = True` and have the program wkhtmltopdf on your system path and it will save the body as pdf instead of HTML/RTF/plain text. You can still make it work if it's not on your path. To do so, simply provide the path for it to the `wkPath` keyword argument. Additionally, if you want to change the formatting wkhtmltopdf uses, you can pass a list of additional parameters to give it through the `wkOptions` keyword argument. For example, if you wanted to save it with the orientation set to landscape, you would call the function like this:
```py
msg.save(pdf = True, wkOptions = ['-O', 'Landscape'])
```

I decided to look at one of my projects that I had for saving to PDF and found that it was mostly code that had already been integrated in one way or another. Stripping away everything that was already in the module, the last thing was an external call to wkhtmltopdf, which has now been added.
