### ISSUE TITLE
extract_msg returned "command not found" after installing via pip

### ISSUE THREAD

**Issue by haruyosh** [TeamMsgExtractor/msg-extractor#171]
Hello team, 

At first I want to say thank you for your great effort to provide this great package.  I am very satisfied with the output from my .msg files.  While installing I had to fix some problems, let me report these.

**Bug Metadata**
* Version of extract_msg: [0.27.9]
* Your python version: Python [3.7.0]
* How did you launch extract_msg?
  - [ ] My command line or
  - [v] I used the extract_msg package

**Describe the bug**
- The installed script `~/.pyenv/versions/anaconda3-5.3.1/bin/extract_msg` did not have execution flag
- The installed script `~/.pyenv/versions/anaconda3-5.3.1/bin/extract_msg` contains CRLF which yielded error on my mac

[ If applicable ]
**What code did you use or can we use to reproduce this error?

```
$ pyenv versions
  system
  3.7.3
* anaconda3-5.3.1 (set by /Users/haruyosh/.pyenv/version)
$ which pip
/Users/haruyosh/.pyenv/shims/pip
$ pip install extract-msg
$ extract_msg 
pyenv: extract_msg: command not found
```

**Additional context**
[Add any other context about the problem here.]
I wrote what I did to fix them here: https://qiita.com/haruyosh/items/20d55e3d0adf408c6ed9 .  Though some comments are written in Japanese, I hope you can follow commands which I issued.

**Comment by TheElementalOfDestruction** [comment]
Technically this should be a part of https://github.com/TeamMsgExtractor/msg-extractor/issues/162 because this is a bug with a feature that is still considered to be in progress. The issue with crlf is being fixed (git is not happy with my right now, and so is not allowing me to make commits). As for the execution flag, I have no idea how to actually set that. I had to figure out on my own how to even have the script added to the bin directory through trial and error. If you could let me know how I actually set the execution bit, that would be great.

**Comment by TheElementalOfDestruction** [comment]
The execute flag should now be working properly in 0.27.10, can you confirm?

**Comment by TheElementalOfDestruction** [comment]
I have received confirmation that this should now be working in version 0.28.0. If I don't get a response in the negative within the week, I will assume you are having no more problems and close this issue.
