### ISSUE TITLE
Import error in Message class - IncompatibleOptionsException

### ISSUE THREAD

**Issue by DChaitanya** [TeamMsgExtractor/msg-extractor#185]
**Bug Metadata**
* Version of extract_msg: 0.28.1

In msg-extractor/extract_msg/message.py on line 59 .
`            raise IncompatibleOptionsException('Only one of the following options may be used at a time: toJSon, raw, html, rtf')
`
However IncompatibleOptionsException is not imported any where.

**Comment by TheElementalOfDestruction** [comment]
I actually forgot to add the exception entirely to the module. It'll be fixed in the next update, I just have to finish running the testing on it to make sure I didn't introduce any new issues. I need to remember to properly test the what the module does when you do something wrong rather that just when you do something right.

**Comment by TheElementalOfDestruction** [comment]
This should be fixed now. Let me know if you have any more issues.

**Comment by DChaitanya** [comment]
Thanks for quick update.
