### ISSUE TITLE
Saving file attachments 

### ISSUE THREAD

**Issue by DChaitanya** [TeamMsgExtractor/msg-extractor#197]
As i go through the code of save method, you are created new directory based on msg date and subject under the customPath user specified and finally returns class instance.
So it is difficult to get new directory name from save method, can you please make dirName as class variable, so it can easily accessible from outside.

`d = self.parsedDate
        if d is not None:
            dirName = '{0:02d}-{1:02d}-{2:02d}_{3:02d}{4:02d}'.format(*d)
        else:
            dirName = "UnknownDate"
            
        if self.subject is None:
            subject = "[No subject]"
        else:
            subject = "".join(i for i in self.subject if i not in r'\/:*?"<>|')

        self.dirName = dirName + " " + subject`

**Comment by TheElementalOfDestruction** [comment]
There are plans to rewrite large sections of the saving code, and I am not sure this section will even make it. I will, however, make it so that any code it does end up using to determine the path for the output will be accessible through a function when that happens.

**Comment by TheElementalOfDestruction** [comment]
Right now about the best I could do is provide a property that gives you access to the return of that code. However there is code later in the save function that might add a number to the end of it should the folder already exist in the save directory. As this code is run only on saving and the result will depend on the save location, it is not easy to enable access to it through a function. I'm hoping the raw name will be sufficient, otherwise we may need to explore alternative options. If you would like to discuss alternative options in depth, we can either try to do so here or on the MSG Extractor Discord.

Thank you for your time.

**Comment by TheElementalOfDestruction** [comment]
Should now be much easier to get the name that an attachment will be using in version 0.29.0. Let me know if you have any problems with it
