### ISSUE TITLE
Add method to generate htmlBody from rtfBody.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [TeamMsgExtractor/msg-extractor#225]
Scheduled for version 0.30.*, when Python 2 will no longer be supported, I plan to add the feature for encapsulated HTML in the RTF body to be extracted and usable as the htmlBody if no stream can be found. Plans to use https://github.com/seamustuohy/RTFDE are being considered.

@seamustuohy I would like to get in touch with you about the implementation of the library with this one. I also have knowledge of how the encapsulated HTML typically handles attachments so may be able to help you with that known issue. You can contact me on the discord, by email (both are in the README) or we can try to have some conversations here. Now that the next major version won't be using Python 2, the library will be compatible. Let me know what you think.

(Fixed title because I forgot to finish writing it after I got distracted, lol)

**Comment by TheElementalOfDestruction** [comment]
Feature has been implemented.

**Comment by seamustuohy** [comment]
I just got your recent issue in RTFDE. Happy to discuss! I'll reach out later this week when I have had some time to sit down and refresh myself on the RTF encapsulation specs. (It's been a bit since I've dug into them.) 

Also... My apologies for the silence. Better late then never I guess. :grimacing:
