### ISSUE TITLE
UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Outlook.Recall"

### ISSUE THREAD

**Issue by wpnbos** [TeamMsgExtractor/msg-extractor#232]
**Bug Metadata**
* Version of extract_msg: [0.30.2]
* Your python version: Python [3.9.7]
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**
Upon calling extract_msg.openMsg() on a particular .msg file the title error rises. 

I sadly can't share the particular .msg file. 

**Traceback**
```
File "/Users/william/Documents/.../venv/lib/python3.9/site-packages/extract_msg/utils.py", line 539, in openMsg
    raise UnrecognizedMSGTypeError(f'Could not recognize msg class type "{ct}".')
extract_msg.exceptions.UnrecognizedMSGTypeError: Could not recognize msg class type "IPM.Outlook.Recall".
```

**Comment by TheElementalOfDestruction** [comment]
Okay, it's a bug that this was unrecognized as I can find a listing for it. However it being unsupported (that would be the correct error) is a feature request. Unfortunately MSG files come in a wide variety of flavors. Use `strict = false` as a parameter and it will read it using the MSGFile class so you can at least inspect the streams if you need to for the time being. I'll fix the bug and then we can make a feature request for adding support.

Just need to know one thing, when you open the msg file without outlook, does it open like it's a normal message or does it look like it has a special format to it?

**Comment by wpnbos** [comment]
Thanks for the quick help! When viewing the file in textedit it looks like other .msg files. The usual gibberish at the top with XML-like formatting towards the end.

**Comment by TheElementalOfDestruction** [comment]
Yeah, that's because It's a compound/archive file (think similar to a zip file). If you can manage to open it with outlook (or something similar) you get to see what it is really supposed to look like. I don't have anything in the main documents, just a note about it existing in the first place, so I need to see if I can track down an actual reference for it so I can implement it later.

Also, this should now be fixed in both branches of the module. It should not correctly give `UnsupportedMSGTypeError` instead of `UnrecognizedMSGTypeError`.

**Comment by TheElementalOfDestruction** [comment]
@wpnbos I'm trying to look into this type but have yet to find any kind of documentation on it. Would you mind sending me the results of the following bits of code? They only tell what properties and streams are in the file, and should not have any form of sensitive information. You only need to change one thing which is the path for the file:
```py
import extract_msg
import pprint

# Replace the value here with the actual path to the file.
MSG_PATH = 'path/to/msgfile.msg'

with extract_msg.openMsg(MSG_PATH, strict = False) as msg:
    print('#### Outputting regular stream names:')
    pprint.pprint(msg.listDir())

    print('\n#### Printing out property IDs:')
    msg.mainProperties.pprintKeys()
```

This will help me get started on some kind of basic implementation, and tell me if I can use `MessageBase` as the base class for it instead of just MSGFile. Thanks.

**Comment by wpnbos** [comment]
@TheElementalOfDestruction certainly, I'd be glad to help. I'll try to get to it as soon as I have time
