### ISSUE TITLE
Add functionality to extract IP addresses, URLs, Signatures from .MSG 

### ISSUE THREAD

**Issue by deFr0ggy** [TeamMsgExtractor/msg-extractor#292]
It will be great if functionality can be added to extract the URLs, IP Addresses and Signatures from the message body!

**Comment by deFr0ggy** [comment]
Also, it would be great if we can scrape out the emails from the MSG as well!

**Comment by TheElementalOfDestruction** [comment]
It sounds like you are asking for direct implementations of data analysis features (identifying URLs, IP addresses (I don't even know if those are stored anywhere but the header), and email addresses), something that is considered beyond the scope or this project (excluding places where this information may already be provided directly through a property).

Much of those analysis would be better handled by grabbing the data where the information would be present and giving it to a separate library rather than by either trying to piece one together myself or by adding another dependency to the list.

The only thing I don't know what you are asking for is signatures. I'm assuming you mean something that could find the end of an email for the signature, but that would *also* be beyond the scope of the project, unless those are directly stored to a property.

**Comment by deFr0ggy** [comment]
Hey @TheElementalOfDestruction! 

Thank for the reply! I have managed to grab the required details. It's just to work with the data returned in the **.body**. It can be used to fetch the required details using some REGEX FTW. 

![image](https://user-images.githubusercontent.com/16836050/192528672-3f84940b-27d0-4c14-8f4b-802717f7b4a1.png)

**Comment by TheElementalOfDestruction** [comment]
Feature request has been rejected as it is considered beyond the scope of the project and would require additional work to ensure it remains functional. Maybe a later version will have something for it, but it would probably be after the 1.0.0 release.
