### ISSUE TITLE
unsupported MSG types

### ISSUE THREAD

**Issue by piskvorky** [TeamMsgExtractor/msg-extractor#294]
**Bug Metadata**

* Version of extract_msg: 0.36.1
* Your python version: Python 3.8
* How did you launch extract_msg?
  - [ ] My command line or
  - [x] I used the extract_msg package

**Describe the bug**

I'm seeing two errors:

```
MSG type "IPM.Document.Excel.Sheet.12" currently is not supported by the module. If you would like support, please make a feature request.
```

and

```
Could not recognize msg class type "IPM.Microsoft.FolderDesign.NamedView".
```

Both seem to originate from [utils.py](https://github.com/TeamMsgExtractor/msg-extractor/blob/d3b6a43f5460e7128ce525d27b47266bfb10a057/extract_msg/utils.py#L658-L669). I do not have access to the original MSG files unfortunately.

I'm not clear about what these "MSG types" are in the first place. What is MSG of type "IPM.Document.Excel.Sheet.12", for example? Is "Excel.Sheet.12" some type of an email message? What am I looking at?

Based on that, I could either contribute a PR / fix, or ignore the errors as irrelevant. Thanks!

**Comment by piskvorky** [comment]
By the way, looking at `utils.py`, what does the following code do? 

https://github.com/TeamMsgExtractor/msg-extractor/blob/d3b6a43f5460e7128ce525d27b47266bfb10a057/extract_msg/utils.py#L667-L668

Looks like a no-op at a glance.

**Comment by TheElementalOfDestruction** [comment]
As to the original message, this is the intended behavior when a type is not supported by the module, but is recognized as being fully documented or at least mentioned somewhere. The first error is saying we don't (at least not yet) support doing anything with the file except the most basic operations, achievable by using the `strict = False` argument to the open function. The second is saying that the type wasn't recognized period, and therefore likely has no documentation at all.

Both of these are normal to see, and usually indicate you have a pretty special file on your hands.

To put it simply, an msg type is a list of period separated values that specify what the actual file is beyond just being .msg. For example, a contact, email, and appointment all use .msg, but have different data inside of them. We use this value to know what kind of data we are looking at to send the file to the right parsing class. The only thing to fix would be to add a new class designed to parse these types that the module currently cannot.


As for your second message, it's not a no-op. The module is based a lot around cached properties, and that is telling it to load the attachments property into memory immediately instead of waiting for whenever it would be first accessed. The `delayAttachments` argument is used for files with problematic attachments or when you don't care about them at all, so you can tell it to not cache them. It can sometimes be very important that properties are loaded in the right order, which is why some of these are loaded as soon as possible.

**Comment by piskvorky** [comment]
Thanks for the super fast reply.

If I understood correctly, the `IPM.Document.Excel.Sheet.12` type means this is a MSG file that is really an Excel sheet – but with a wrong file extension? I.e. it could be enough to rename `.msg` => `.xls` or `.xlsx`, and parse as normal Excel.

Or is it really a recoding of Excel content into a special MSG format, which would need a special dedicated parser?

**Comment by TheElementalOfDestruction** [comment]
Looks to just be a excel file. The old word files and excel files shared a format. I believe you want .xls

**Comment by TheElementalOfDestruction** [comment]
I didn't actually notice the second type you specified the first time around, but I'm looking into some information on it. I'm actually not entirely sure if it would even be a message (if you can open it in outlook as a message then I guess that answers that question) but it contains certain data I don't know how to use yet. If you can confirm it as a message I may be able to add support for it at some point in the future.

**Comment by TheElementalOfDestruction** [comment]
I'm also double checking the first one and it looks like it has a class type and as much may actually be a form of MSG file I've just never seen, as excel files don't use the same property names. I'm trying to work out how something would actually *get* that tag to figure out how (if at all) to handle it, so I may end up reopening this
