### ISSUE TITLE
show whole message as string? (is it possible/feature request)

### ISSUE THREAD

**Issue by corobin** [TeamMsgExtractor/msg-extractor#343]
* Version of extract_msg: 0.39.1
* Your python version: Python 3.11.2 64-bit
* How did you launch extract_msg?
  - both command line and package

Hello,

I am not sure if this functionality already exists. I will describe what problem I encountered and what I wish to do to avoid the XY problem.

Problem: I noticed that .msg files are not deterministic. In other words, if I drag *the same* email out from Outlook twice, the two .msg files that are created are not identical. So I cannot directly use filecmp to find duplicate .msg files.

The thought came up of using extract_msg to compare the contents instead. in order to do so, i would need a way to get *all* of the contents (including headers, body, attachments) in a format that can be compared. the simplest i have thought of is just getting a string representation of the whole message much like what an .eml file would contain, and then just comparing the strings. (comparing the `extract_msg.message.Message` object directly does not appear to work).

Question: is this a function that already exists in extract_msg? If not, perhaps this can be treated as a feature request?

Thanks.

**Comment by TheElementalOfDestruction** [comment]
This is not a function that already exists, however message files have several things designed to identify two messages as being the same. MessageBase (the parent class for most of the module) has the `messageId` property which is how such comparisons are usually done. 

Aside from that, headers, body, etc can all be retrieved from different properties

**Comment by corobin** [comment]
oh ok, so what i've been able to do so far is to retrieve the different headers by name one by one, what is the canonical way to get *all* the headers in a message?

it seems like messages really only come in 3 parts total: headers, body, attachments

so i should be able to just loop through them to get everything i need as long as i can enumerate everything, is this on the right path?

**Comment by TheElementalOfDestruction** [comment]
They *sort of* come in those parts, but the problem is that the module hides a lot of garbage about the "standard" from the user. The stream that contains the unprocessed headers isn't a mandatory stream, so it can end up just being entirely omitted. If it *is* present, you can use `msg._getStringStream('__substg1.0_007D')` to get the raw data, otherwise the module does what it can to hide the fact that it doesn't actually exist.

Past that single detail, everything becomes significantly more complicated. Bodies come in 3 possible forms, often with more than one being present on the message: HTML, RTF, and plain text. These *should* generate rather consistently, but that is because I believe the are already generated before the message is ever saved, and outlook doesn't generate any that are missing. 

The attachments are an even bigger issue, only possibly having some kind of unique identifier to them. If they aren't an MSG file you could compare the raw bytes of the attachment to another to see if they are identical, but otherwise you have to compare the message like you would the previous one, as its bytes are not provided. You *can* get the raw bytes for a message from the export method, and so long as the streams and data on two of them are the same, identical files should always be produced because of how the code works. 

With all of that said, MessageID should be the most reliable property to compare against, as it is unique to the message, not the MSG file. It's also used for things like managing reply chains, and IIRC it will be consistent across users involved with an email. Or at least *should* be.

**Comment by corobin** [comment]
darn, that's one messy and complicated format! thanks for the detailed information, I'll have to think about this some more to figure out how to approach it. probably messageid with a fallback using some key parts...
