### ISSUE TITLE
Incorrect encoding

### ISSUE THREAD

**Issue by ShineSSH** [TeamMsgExtractor/msg-extractor#344]
**Bug Metadata**
* Version of extract_msg: [0.38.4]
* Your python version: Python [3.10.5]
* How did you launch extract_msg?
  - [ python -m extract_msg filename.msg ] My command line

**Describe the bug**
Problem with the encodings. Messages are not decoded correctly. Files are written to disk correctly, but part of message and attached file names are in wrong encoding.

Is there a message.msg file you want to share to help us reproduce this?
- [2023-02-19-13-28-04-747.zip](https://github.com/TeamMsgExtractor/msg-extractor/files/10782882/2023-02-19-13-28-04-747.zip)

**Screenshots**
![1](https://user-images.githubusercontent.com/96646176/220073786-ddc729a5-f6c5-4742-83e0-1842dc06f86d.png)

**Comment by TheElementalOfDestruction** [comment]
Encoding detection is based on a property written in the MSG file. I've noticed some seem to have values that don't match the content contained though, and have been trying to figure out why. If you know the correct encoding it can be overridden with the `overrideEncoding` option given to `openMsg` which will fix the text and file names. This isn't a perfect solution, but it may be able to help in some cases while I try to figure out why this happens.

**Comment by TheElementalOfDestruction** [comment]
Finally had a chance to look at your file and I see the problem: it actually has *no* encoding information attached to it. Currently the way that is handled is to default to the encoding ISO-8859-15, log that there is no encoding information, and call it a day. This is based on instructions in the Microsoft docs which specifically use "SHOULD" and "MAY" which means the current approach is perfectly acceptable to Microsoft but may leave problems should the assumption be wrong. 

You can check if the encoding is missing by actually doing exactly what the module does:
```py
if not (msg.areStringsUnicode or msg.props.has_key('3FFD0003')):
```
If that if block evaluates to True, you may need to do some manual handling to correct the encoding data. I can try to add a blurb about some of this in the wiki/docs. Basically you use some data from the msg file (the body would be good, so long as you encode it in ISO-8859-15 to get back to the original bytes for encoding detection), use that to detect the encoding, close the file, then reopen it with the encoding overriden. A future version may have a way to clear all the necessary fields to make it so that live encoding changes can be done without issues.

**Comment by TheElementalOfDestruction** [comment]
Working on some additional encoding stuff to make it easier to properly identify some MSG files. Some of the code I'm implementing will actually fix the issue for your specific file, allowing it to properly be detected.
