### ISSUE TITLE
Is it possible to substitute image names where they appear in the message?

### ISSUE THREAD

**Issue by DPleckauskas** [TeamMsgExtractor/msg-extractor#348]
I'm looking at parsing `.msg` files which this is a great tool for, my email file has images and these get correct identified by the tool however the order of these is lost. Would be great is to have the image name substituted in place of where the image was found, does this already exist? Also would be great to have an identifier for a table.

```
some message text
image01.png
```

```
some message

***table start***
header
data
***table_end***
```

**Comment by TheElementalOfDestruction** [comment]
No, there is not a way to tell the module you want to replace the images with text, not without adding your own code that does that.

Unfortunately, the rest of the issue is too vague for me to provide any direct help with without an actual file, as it relies on looking at the underlying data to figure out how it is setup to know how to process it.

One thing I noticed is that you said the order of images is lost, however AFAIK there is no code in the module that is capable of actually doing this, unless the calls to bs4 are somehow reordering image tags (which would *probably* be something to report to them. You could check this by looking for the image tags in the htmlBody property and seeing if that is the order they are coming out as).

As for tables, again it's too vague for me to really do anything about without having some kind of look at the data.

It's unlikely the module will receive that as a feature,
Requiring a not insignificant amount of additional code to make it possible, and also requiring a new argument in several places that will make things even more cluttered. Instead, if you desire it you can replace the `getSaveBody` methods (`getSaveBody` for plain text, `getSaveHtmlBody` for HTML, `getSavePdfBody` for PDF (though a change to `getSaveHtmlBody` is enough to change the HTML content that produces the PDF), and `getSaveRtfBody` for RTF). In the code you replace, you can add lines that will do the processes you want.
