### ISSUE TITLE
Non msg containers embedded as attachments cause all attachments to fail

### ISSUE THREAD

**Issue by 0x3a** [TeamMsgExtractor/msg-extractor#87]
There is a `NotImplemented` exception check for non msg containers: https://github.com/mattgwwalker/msg-extractor/blob/master/extract_msg/attachment.py#L47

This exception is never really handled and simply bubbles up too far, I can't handle the exception and then force it to continue parsing other attachments. If this exception occurs there will be no `self._attachments` attribute for the Message object. Might be worth it to either initialize the items that are parseable (and raise an informative log f.e) or simply make sure there's an empty `_attachments` property.

**Comment by TheElementalOfDestruction** [comment]
This feature has been accepted. To make sure I don't forget my plans, I will write them here. 

Add an option to msg files that signifies attachment errors should be ignored. This lets the class know that if an error occurs it should add a different attachment class to the list of attachments: `UnsupportedAttachment`. The passed option will specify what level of ignoring should be done. 1 option would only ignore the `NotImplemented` error, while another would also add a class called `BrokenAttachment` for any attachment that causes major errors that are not caused by it not being supported.


I'm sorry it took so long for this to be accepted. I have been debating for a while on how to make this work in a way that would inform the user that an attachment failed, but had trouble figuring it out. I'll update you when this feature is being worked on or is implemented.

**Comment by TheElementalOfDestruction** [comment]
I believe this feature is now ready to be used. I just have to finish some final testing before a release will be pushed out.

**Comment by TheElementalOfDestruction** [comment]
Version 0.28.0 Has been release with support for this feature. All msg classes now have an additional option known as `attachmentErrorBehavior` which can be used to specify how attachment exceptions are handled.

**Comment by TheElementalOfDestruction** [comment]
This issue has been closed. If you believe this issue should be reopened, please inform us as to why. Thank you.
